### ISSUE TITLE
Quota Information

### ISSUE THREAD

**Issue by CopperCat** [DivinElegy/roll.divinelegy#5]
There is currently nowhere to find information on what the Quota means (whether it is for download/upload, when it resets, what counts towards the quota).

Adding this would be helpful to new users.

**Comment by cameron1729** [comment]
Thanks. It is for downloading files from DivinElegy. You receive a notification about it when you attempt to download a file from the site.

I agree, adding a tooltip or something similar to the quota information on the right would be helpful.
