### ISSUE TITLE
Public Profile - Display Name + Country Not Saving

### ISSUE THREAD

**Issue by dguzek** [DivinElegy/roll.divinelegy#8]
On the live site, users are allowed to edit their *display name* and *country* under **My Arrows/Public Profile**.  Clicking *Save* notifies users that their details have been "Saved!" but it seems that the values are not, in fact, actually saved to the database.

It may also be worth noting that various JavaScript files on the production site still have `console.log` statements for debugging, but that probably isn't worth its own GitHub issue!

**Comment by cameron1729** [comment]
This issue was moved to DivinElegy/rock.divinelegy#9

**Comment by cameron1729** [comment]
Hey Dan, I moved this issue over to our other repository. I believe it is fixed now, but if you could test and leave a comment over at https://github.com/DivinElegy/rock.divinelegy/issues/9 that would be appreciated. Thanks :]
