### ISSUE TITLE
Sort by Newest/Upload Date

### ISSUE THREAD

**Issue by Arauna** [DivinElegy/roll.divinelegy#9]
As you load 100% of the list into the javascript as soon as they load the page, you have the date uploaded, can you please add a sort based off it?

If you would like help changing that, so that instead of loading all of the database into their browser, I volunteer to make both a php, ajax and js script to show you how to implement it.

**Comment by Arauna** [comment]
Other improvement ideas.  When you change the Artist or any of the like, on the first keyup or change whichever you use reset the page to 1.

**Comment by cameron1729** [comment]
There is a good reason the entire list is sent like that. Doing it the way you propose is not practical for our purposes unfortunately.
